(() => {
  const css = `
  .fashion-art{width:100%;aspect-ratio:300/380;display:grid;place-items:center;background:linear-gradient(145deg,#fffdf8,#eee8df);overflow:hidden;position:relative}
  .fashion-art:before{content:"";position:absolute;inset:0;background:radial-gradient(circle at 18% 20%,rgba(255,255,255,.92) 0 2px,transparent 3px);background-size:23px 23px;opacity:.4}
  .fashion-art svg{width:90%;height:90%;position:relative;z-index:1;filter:drop-shadow(0 14px 11px rgba(37,28,18,.16))}.fashion-art .cloth{stroke:#17120f;stroke-width:3.2;stroke-linejoin:round}.fashion-art .seam{fill:none;stroke:#17120f;stroke-width:1.8;opacity:.5}.fashion-art .print{fill:#17120f;font-family:Arial,sans-serif;font-weight:900}.card>.fashion-art{border-bottom:1px solid var(--line)}.thumb .fashion-art{aspect-ratio:1}.thumb .fashion-art svg{width:95%;height:95%}
  #builder{padding-top:22px}.look-shell{background:#fff;border:1px solid var(--line);border-radius:30px;padding:18px;box-shadow:var(--shadow)}.look-head{display:flex;justify-content:space-between;align-items:flex-start;gap:12px;margin-bottom:14px}.look-head h2{font-size:clamp(25px,4vw,36px);letter-spacing:-.05em;margin:0 0 4px}.look-head button{border:0;background:#eee;border-radius:999px;padding:11px 16px;font-weight:850}.look-studio{display:grid;grid-template-columns:126px minmax(0,1fr) 126px;gap:14px;min-height:560px}.selected-rail{display:flex;flex-direction:column;gap:9px}.selected-mini{border:2px solid transparent;background:#f2eee8;border-radius:19px;padding:7px;text-align:center;transition:.2s}.selected-mini.active{border-color:#111}.selected-mini .fashion-art{aspect-ratio:1;border-radius:13px}.selected-mini b{display:block;font-size:11px;margin-top:4px}.selected-mini small{display:block;font-size:8px;color:var(--muted);line-height:1.15}.empty-choice{aspect-ratio:1;border:2px solid #111;border-radius:14px;display:grid;place-items:center;font-size:31px;background:#fff}
  .avatar-stage-pro{position:relative;overflow:hidden;border-radius:26px;background:radial-gradient(circle at 20% 20%,rgba(255,255,255,.85) 0 3px,transparent 4px),linear-gradient(145deg,#ead5ff,#fff 53%,#e4ff69);background-size:27px 27px,auto;display:grid;place-items:center}.avatar-person{position:relative;width:min(360px,76%);height:520px}.avatar-hair{position:absolute;left:50%;top:12px;translate:-50% 0;width:105px;height:65px;background:#2b211b;border:4px solid #111;border-radius:58% 58% 36% 36%;z-index:3}.avatar-face{position:absolute;left:50%;top:35px;translate:-50% 0;width:88px;height:108px;background:#d2a078;border:4px solid #111;border-radius:45% 45% 48% 48%;z-index:2}.avatar-face:after{content:"";position:absolute;left:28px;bottom:23px;width:28px;height:8px;border-bottom:3px solid #7d4d44;border-radius:50%}.avatar-neck{position:absolute;left:50%;top:127px;translate:-50% 0;width:37px;height:35px;background:#d2a078;border-inline:4px solid #111}.avatar-body{position:absolute;left:50%;top:150px;translate:-50% 0;width:150px;height:190px;background:#d2a078;border:4px solid #111;border-radius:38px 38px 24px 24px}.avatar-leg{position:absolute;top:328px;width:62px;height:175px;background:#d2a078;border:4px solid #111;border-radius:20px}.avatar-leg.left{left:93px}.avatar-leg.right{right:93px}#avatarLayers{position:absolute;inset:0;z-index:8}.look-layer{position:absolute;left:50%;translate:-50% 0;width:270px;pointer-events:none;animation:dressIn .26s cubic-bezier(.2,.8,.2,1)}.look-layer svg{width:100%;height:100%;filter:drop-shadow(0 9px 8px rgba(0,0,0,.13))}.look-layer.bottom{top:277px;height:240px;z-index:1}.look-layer.top{top:118px;height:275px;z-index:2}.look-layer.layer{top:105px;height:300px;z-index:3}.look-layer.outer{top:91px;height:330px;z-index:4}@keyframes dressIn{from{opacity:0;transform:scale(.88) translateY(-8px)}to{opacity:1;transform:none}}
  .action-rail{display:flex;flex-direction:column;justify-content:center;gap:20px}.action-rail button{border:0;background:transparent;font-size:10px;font-weight:900;line-height:1.15}.action-rail span{display:grid;place-items:center;width:70px;height:70px;margin:0 auto 6px;background:#fff;border-radius:50%;font-size:31px;box-shadow:0 8px 24px rgba(0,0,0,.09);transition:.18s}.action-rail button:active span{transform:scale(.9)}
  .builder-tabs{display:flex;gap:9px;overflow-x:auto;padding:20px 0 12px;scrollbar-width:none}.builder-tabs::-webkit-scrollbar,.builder-list::-webkit-scrollbar{display:none}.builder-tabs button{flex:0 0 auto;border:1px solid var(--line);background:#fff;border-radius:999px;padding:11px 17px;font-weight:900}.builder-tabs button.active{background:#111;color:#fff}.builder-list{display:grid;grid-auto-flow:column;grid-auto-columns:150px;gap:10px;overflow-x:auto;padding:2px 0 18px;scroll-snap-type:x mandatory}.look-choice{scroll-snap-align:start;border:2px solid transparent;background:#f3efe9;border-radius:22px;padding:8px;overflow:hidden}.look-choice.active{border-color:#111;background:#fff}.look-choice .fashion-art{aspect-ratio:1;border-radius:15px}.look-choice b{display:block;font-size:12px;margin-top:7px}.look-choice small{display:block;color:var(--muted);font-size:10px;line-height:1.2;min-height:24px}.builder-extra{margin-top:10px}.builder-toast{position:fixed;left:50%;bottom:calc(24px + env(safe-area-inset-bottom));z-index:500;transform:translate(-50%,20px);background:#111;color:#fff;border:2px solid var(--lime);border-radius:999px;padding:13px 18px;font-weight:900;opacity:0;pointer-events:none;transition:.28s;white-space:nowrap}.builder-toast.show{opacity:1;transform:translate(-50%,0)}
  @media(max-width:760px){#builder{padding-top:15px}.look-shell{padding:12px;border-radius:24px}.look-studio{grid-template-columns:80px minmax(0,1fr) 72px;gap:6px;min-height:420px}.selected-mini{padding:4px;border-radius:14px}.selected-mini .fashion-art{border-radius:9px}.selected-mini b{font-size:9px}.selected-mini small{font-size:7px}.avatar-stage-pro{border-radius:20px}.avatar-person{width:260px;height:405px;transform:scale(.8);transform-origin:center}.action-rail{gap:13px}.action-rail span{width:54px;height:54px;font-size:24px}.action-rail button{font-size:8px}.builder-list{grid-auto-columns:116px}.look-choice{border-radius:17px}.look-head button{font-size:12px;padding:9px 11px}}
  `;
  const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);

  function hex(text=''){
    const s=text.toLowerCase();
    if(s.includes('чёрн')||s.includes('черн')) return '#202020'; if(s.includes('бел')||s.includes('молоч')) return '#f2efe7';
    if(s.includes('голуб')) return '#8fc8ee'; if(s.includes('розов')) return '#e8a6b8'; if(s.includes('горч')||s.includes('жёл')||s.includes('жел')) return '#e3a51c';
    if(s.includes('олив')) return '#777653'; if(s.includes('графит')||s.includes('сер')) return '#686a6d'; if(s.includes('песоч')||s.includes('беж')) return '#c5aa79'; return '#777';
  }
  function artSvg(x){
    const c=hex(x.color), dark='#17120f', gid='g'+x.id.replace('-',''); const fill=`url(#${gid})`;
    const defs=`<defs><linearGradient id="${gid}" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${c}"/><stop offset=".62" stop-color="${c}"/><stop offset="1" stop-color="#000" stop-opacity=".18"/></linearGradient></defs>`;
    let s='';
    if(x.cat==='Брюки') s=`<path class="cloth" fill="${fill}" d="M66 32h100l14 56-22 247h-43l-13-171-12 171H47L25 88z"/><path class="seam" d="M66 32q42 18 100 0M102 45v119M52 91h40M115 91h40"/>`;
    else if(x.cat==='Шорты') s=`<path class="cloth" fill="${fill}" d="M56 55h120l13 61-26 126h-48l-15-70-16 70H36L10 116z"/><path class="seam" d="M56 55q48 16 120 0M100 65v107"/>`;
    else if(x.cat==='Худи') s=`<path class="cloth" fill="${fill}" d="M56 82q44-50 88 0l31 17 39 37-24 42-29-17v139H39V161l-29 17-24-42 39-37z"/><path class="cloth" fill="${fill}" d="M60 81q3-55 40-55t40 55q-40-24-80 0z"/><path class="seam" d="M64 81q36 29 72 0M71 228h58v37H71zM87 86v58M113 86v58"/>${x.id==='H-01'?'<text class="print" x="5" y="155" font-size="12" transform="rotate(-74 5 155)">BLACKSQUAD</text>':''}`;
    else if(x.cat==='Футболки'||x.cat==='Лонгсливы') {const long=x.cat==='Лонгсливы';s=`<path class="cloth" fill="${fill}" d="M57 57l43 15 43-15 48 28 ${long?'37 159-38 13-24-113':'35 57-36 20-22-47'}v210H34V${long?'158':'115'}L12 ${long?'271 -26 258':'142 -23 122'}l32-37z"/><path class="seam" d="M73 64q27 42 54 0M35 115h130"/>`;}
    else if(x.slot==='layer') s=`<path class="cloth" fill="${fill}" d="M50 51l50 19 50-19 41 28 28 70-35 18-17-39v177H33V128l-17 39-35-18 28-70z"/><path fill="#f5f1e7" stroke="${dark}" stroke-width="3" d="M66 57l34 13-25 40-26-50zM134 57l-34 13 25 40 26-50z"/><path class="seam" d="M100 70v235M46 127h37v36H46M117 127h37v36h-37"/>`;
    else {const coat=x.id==='J-04', varsity=x.id==='J-02';s=`<path class="cloth" fill="${fill}" d="M49 47l51 20 51-20 44 28 31 77-37 18-20-49v${coat?210:184}H31V121l-20 49-37-18 31-77z"/><path class="seam" d="M70 57q30 28 60 0M100 67v${coat?330:306}M47 175h42M111 175h42"/>${varsity?`<path d="M4 77l45-30 20 18-39 247-39-17zM196 77l-45-30-20 18 39 247 39-17z" fill="#eee4d2" stroke="${dark}" stroke-width="3"/><circle cx="62" cy="125" r="18" fill="#d92e2e" stroke="${dark}" stroke-width="3"/>`:''}`;}
    return `<svg viewBox="-30 0 260 360" aria-hidden="true">${defs}${s}</svg>`;
  }
  function art(x,cls='fashion-art'){return `<div class="${cls}" data-art="${x.id}">${artSvg(x)}</div>`}

  function init(){
    if(typeof items==='undefined'||typeof byId==='undefined'||typeof selected==='undefined'||typeof renderBuilder!=='function'||typeof renderCatalog!=='function') return setTimeout(init,100);
    const oldPic=pic;
    pic=function(key){const x=items.find(i=>i.flatKey===key);return x?art(x):oldPic(key)};
    renderCatalog();

    const builder=document.querySelector('#builder'); if(!builder) return;
    builder.innerHTML=`<div class="look-shell"><div class="look-head"><div><h2>Соберём лук, сучечка?</h2><div class="preview-code" id="lookCode">Ничего не выбрано</div></div><button id="clearV2">↻ Сбросить</button></div><div class="look-studio"><aside class="selected-rail" id="selectedRail"></aside><div class="avatar-stage-pro"><div class="avatar-person"><div class="avatar-hair"></div><div class="avatar-face"></div><div class="avatar-neck"></div><div class="avatar-body"></div><div class="avatar-leg left"></div><div class="avatar-leg right"></div><div id="avatarLayers"></div></div></div><aside class="action-rail"><button id="randomV2"><span>⤨</span>Случайный<br>образ</button><button id="saveV2"><span>♡</span>Сохранить<br>образ</button><button id="tryonV2"><span>✦</span>Создать запрос<br>на примерку</button></aside></div></div><div class="builder-tabs" id="builderTabs"></div><div class="builder-list" id="builderItems"></div><div class="builder-extra"><div class="occasion" id="occasionsV2"></div><div class="score"><div><b>Оценка сочетания</b><small id="scoreNoteV2">Выбери хотя бы две вещи.</small></div><strong id="scoreNumberV2">—</strong></div><div class="request" id="requestV2"></div></div>`;
    const toast=document.createElement('div');toast.className='builder-toast';toast.id='builderToast';document.body.appendChild(toast);
    let slot='outer'; const slots=['outer','layer','top','bottom']; const names={outer:'Верхняя одежда',layer:'Рубашки / слой',top:'Толстовки и футболки',bottom:'Брюки и шорты'};
    function code(){return slots.map(s=>selected[s]).filter(Boolean).join(' + ')}
    function draw(){
      document.querySelector('#lookCode').textContent=code()||'Ничего не выбрано';
      document.querySelector('#selectedRail').innerHTML=slots.map(s=>{const x=byId(selected[s]);return `<button class="selected-mini ${slot===s?'active':''}" data-slot-v2="${s}">${x?art(x):'<div class="empty-choice">−</div>'}<b>${x?x.id:'—'}</b><small>${x?x.name:names[s]}</small></button>`}).join('');
      document.querySelectorAll('[data-slot-v2]').forEach(b=>b.onclick=()=>{slot=b.dataset.slotV2;draw()});
      document.querySelector('#avatarLayers').innerHTML=['bottom','top','layer','outer'].map(s=>{const x=byId(selected[s]);return x?`<div class="look-layer ${s}">${artSvg(x)}</div>`:''}).join('');
      document.querySelector('#builderTabs').innerHTML=slots.map(s=>`<button class="${slot===s?'active':''}" data-tab-v2="${s}">${names[s]}</button>`).join('');
      document.querySelectorAll('[data-tab-v2]').forEach(b=>b.onclick=()=>{slot=b.dataset.tabV2;draw()});
      const list=items.filter(x=>x.slot===slot);
      document.querySelector('#builderItems').innerHTML=`<button class="look-choice ${!selected[slot]?'active':''}" data-choice-v2=""><div class="empty-choice">−</div><b>Без вещи</b><small>Убрать слой</small></button>`+list.map(x=>`<button class="look-choice ${selected[slot]===x.id?'active':''}" data-choice-v2="${x.id}">${art(x)}<b>${x.id}</b><small>${x.name}</small></button>`).join('');
      document.querySelectorAll('[data-choice-v2]').forEach(b=>b.onclick=()=>{selected[slot]=b.dataset.choiceV2||null;draw();try{sound('success');vibrate([12])}catch(e){}});
      const sc=typeof scoreLook==='function'?scoreLook():{n:0,t:'Выбери хотя бы две вещи.'};document.querySelector('#scoreNumberV2').textContent=sc.n?sc.n+'/100':'—';document.querySelector('#scoreNoteV2').textContent=sc.t;
      if(typeof occasions!=='undefined') document.querySelector('#occasionsV2').innerHTML=occasions.map(o=>`<button>${o}</button>`).join('');
    }
    document.querySelector('#clearV2').onclick=()=>{selected={outer:null,layer:null,top:null,bottom:null};draw()};
    document.querySelector('#randomV2').onclick=()=>{slots.forEach(s=>{const a=items.filter(x=>x.slot===s);selected[s]=(s!=='bottom'&&Math.random()<.2)?null:a[Math.floor(Math.random()*a.length)]?.id||null});draw();try{sound('success');vibrate([15])}catch(e){}};
    document.querySelector('#saveV2').onclick=()=>{if(!code())return alert('Сначала выбери вещи');const a=JSON.parse(localStorage.getItem('kostyaLooks')||'[]');a.unshift({...selected,date:new Date().toLocaleDateString('ru-RU')});localStorage.setItem('kostyaLooks',JSON.stringify(a.slice(0,50)));showToast('✓ Образ сохранён')};
    document.querySelector('#tryonV2').onclick=async()=>{if(!code())return alert('Сначала выбери вещи');const chosen=slots.map(s=>byId(selected[s])).filter(Boolean);const text=`Создай максимально фотореалистичную фотографию меня в комплекте ${code()} из моего цифрового гардероба. Вещи: ${chosen.map(x=>x.name).join(', ')}. Используй мои загруженные фотографии как строгий референс личности, фигуры и одежды. Не изменяй лицо, возраст, причёску, пропорции тела, вес, объём живота, плеч, рук и ног. Точно сохрани татуировки. Одежду воспроизведи максимально близко к оригиналам: цвет, материал, принты, логотипы, длина, объём, крой и естественная посадка. Полный рост, фронтальный ракурс, мягкое нейтральное освещение, без ретуши.`;document.querySelector('#requestV2').style.display='block';document.querySelector('#requestV2').textContent=text;try{await navigator.clipboard.writeText(text);showToast('✓ Запрос скопирован')}catch(e){showToast('Выдели текст ниже и скопируй')}};
    function showToast(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2000)}
    renderBuilder=draw; draw();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
